### ISSUE TITLE
Anything for ExponentialUtilities.jl?

### ISSUE THREAD

**Issue by ChrisRackauckas** [Jutho/KrylovKit.jl#22]
Hey, I saw that you added some phiv calculations and was wondering if you tested against ExponentialUtilities.jl to see if there's anything we should upstream for use in DifferentialEquations.jl. FWIW we haven't seen fantastic results of exponential integrators against well-tuned IMEX methods, and I'm curious to find out if there's any possible improvements to the standard Krylov phiv methods.

**Comment by Jutho** [comment]
Hi @ChrisRackauckas , I don't think there is anything here that is would be relevant, as the implementation here is probably less advanced than that in ExponentialUtilities.jl (and based on the same reference of Niesen & Wright). I guess one difference is that I don't rely on an `opnorm`, as this is often difficult to compute and annoying to bother the user with. I might just use the norm of `A` times a random normalized vector internally, but I don't quite remember.

I think Krylov exponentiation is popular in the context of quantum mechanics, because, approximating the Schrodinger equation in some subspace still gives you a linear ODE with a hermitian matrix, and then using Krylov exponentiation still leads to exact conservation of the norm of the state and its energy. 

There are likely other methods out there which share this property, however, it is sometimes hard to find one ways among all the different methods if one is not a specialist.

**Comment by ChrisRackauckas** [comment]
Okay cool, just digging around. Thanks for the update! I think not relying on opnorm would be a good idea.

**Comment by Jutho** [comment]
You're very welcome; thanks for your interest.

By the way, I might at some point want to rely on your amazing expertise with ODEs/PDEs.

I have a high-dimensional ODE (resulting from applying the Dirac-Frenkel time-dependent variational principle to a variational manifold), where the degrees of freedom are a couple of square matrices `A1, A2, ...`, but which satisfy a certain constraint (e.g. `A1'*A1 + A2'*A2 + ... = 1`) . This constrained is conserved by the differential equation, but cannot be exploited directly (i.e. to eliminate one of the matrices or some of the degrees of freedom in one or the other way). Furthermore, the differential equation also conserves some kind of energy (its actually a Hamiltonian system, but with gauge freedom) which is a highly non-linear function of the degrees of freedom. Finally, the ODE is most likely stiff. 

So far, I have not had a great deal of success in coming up with ways to solve this ODE problem. If you have some time and interest to talk about this at some point, let me know.
