### ISSUE TITLE
`eigsolve` is unable to resolve degeneracies

### ISSUE THREAD

**Issue by mwallerb** [Jutho/KrylovKit.jl#23]
Consider the following matrix:
```julia
>>> A = zeros(15,15);
>>> A[[  2,  16,  18,  32,  49,  50,  51,  52,  56,  64,  66,  68,  72,
        79,  80,  84,  88,  94,  98,  99, 101, 110, 112, 113, 114, 117,
       126, 127, 128, 133, 149, 154, 157, 162, 163, 170, 173, 176, 178,
       186, 189, 191, 192, 193, 205, 210, 224]] .= 1;
>>> A[[  3,  31, 150, 220]] .= -1;
```

The eigenvalues of this matrix are degenerate, yet `eigsolve` is unable to resolve this degeneracy and instead returns eigenvalues with multiplicity one:
```julia
>>> eigvals(A)'
[-2.0 -2.0 -2.0 -1.73205 -1.73205 -1.37228 1.0 1.0 1.0 ... 1.0 1.73205 1.73205 4.37228]

>>> evals_k, evecs_k, info = KrylovKit.eigsolve(A, 3, :SR);
>>> evals_k'
[ -2.0  -1.73205  -1.37228  1.0  1.73205  4.37228]
```

This is independent of `which`.  ARPACK (tested using `scipy.sparse.eigs`) instead correctly resolves the degeneracy:
```python
>>> import scipy.sparse.linalg
>>> scipy.sparse.linalg.eigsh(A, k=3, which='SA')[0]
array([-2., -2., -2.])
```

**Comment by Jutho** [comment]
The way Krylov methods construct eigenvectors starting from a random vector `v` is by essentially by making linear combinations of `v`, `A*v`, `A^2*v`, ..., `A^k*v`. 

If you expand `v` in terms of the eigenvectors `v_i` with eigenvalues `λ_i` of `A`, say `v = ∑ c_i * v_i`  , then `A^k v = ∑ c_i * λ_i^k * v_i`, and so by combining them for different `k`, you can try to get most coefficients zero and construct an eigenvector.

Now, if eigenvalues are degenerate (since your example is symmetric, I am assuming matrices are diagonalizable) and have different eigenvectors `v_{i,α}`, we find
`v = ∑ c_{i,α} * v_{i,α}`  , then `A^k v = ∑_i λ_i^k * [  ∑_α c_{i,α} * v_{i,α} ]`. 
Now by making linear combinations for different `k`, you can in principle never change the specific linear combination and thus only create a single eigenvector with eigenvalue ` λ_i`, namely `∑_α c_{i,α} * v_{i,α}` (up to normalization). For your example, where one of the 15 eigenvalues is 3-fold degenerate (and the others are not degenerate), it also means that `A^k v` at most leads to a 12 dimensional invariant subspace (`k = 0, ..., 11`) , i.e. `A^12 *v` can completely be expressed as a linear combination of the `A^k*v` with `k< 12`.

That's the theory, in practice the finite numerical precision is what allows these results to be violated. For such a small matrix, the size (15) is smaller than the typical default value for the krylov dimension (the maximal `k` in the linear combinations). I guess that python just notices that `length(v)` is smaller than the Krylov dimension, and generates a complete basis, which works because `A^12 *v` will contain a slight component (of order machine precision) outside of the space spanned by `A^k * v` for `k<12`. It uses this small component and blows it up to a unit vector, and so forth.

My package, KrylovKit.jl, cannot rely on `length(v)`, because it does not even assume that the vectors are actual `AbstractVector` or even `AbstractArray` objects. As such, the only thing it can do when it reaches an invariant subspace (up to machine precision) is quit. 

I think in a practical setting, i.e. with a matrix much larger than the krylov dimension, you wouldn't notice the difference.

**Comment by mwallerb** [comment]
Thanks for the long explanation!

As a tangent, I got `Arpack.jl` to run, and in fact I find that also there, Arpack resolves the degeneracy correctly, so at least Python does not do any additional magic on top of the plain Arpack routines as you suspected.

If you understand you correctly, then you are saying that it is essentially "luck" whether you can resolve degenerate eigenvalues or not (you need to hope for finite numerical precision to kick you out of the subspace).  In my example matrix, we are unlucky with KrylovKit here, but lucky with Arpack.

This comes an extreme surprise to me, because it would imply a fatal flaw of the Krylov technique, namely: one cannot reliably construct a truncated singular value decomposition of a matrix.  In other words, given a matrix `A` with a two-fold degenerate dominant singular value, say `sigma = [1, 1, 0.8, 0.5, ...]`, searching for eigenvalues of `A' * A` with Krylov potentially never recovers any reasonable approximation of the matrix.  For the same reason, I think it would also kill convergence guarantees for low-energy approximations to Hamiltonians and matrix exponentials.  If this is indeed the case, I think one should put in 100-pt flaming letters on every website...

As another tangent, I have experimented with matrices of different sizes that come from fermionic many-body problems (where I know the correct degeneracy of the lowest eigenvalue).  Unfortunately, these are too big to post, but it turns out, Arpack.jl is able to always resolve the degeneracy for the cases I tested, and KrylovKit also gets it once the problems become bigger.

**Comment by Jutho** [comment]
Again, in real life applications, i.e. big problems, numerical errors at machine precision level is what saves you. This is easiest to see when looking for the largest magnitude eigenvalue, but the point of Krylov methods is that they work for any eigenvalue which can become the largest magnitude eigenvalue by rotating or shifting the spectrum in the complex plane (as the rotated/shifted operator would generate the same Krylov subspace). Using the arguments from above, once the first largest magnitude eigenvalue/eigenvector converges, the rest of the Krylov subspace should be orthogonal to that corresponding eigenspace, even if the eigenvalue is degenerate. However, the smallest numerical error which brings in a component along a second eigenvector corresponding to that largest magnitude eigenvalue, even though it is only at machine precision, is sufficient to then, by repeated application of the linear operator, be blown up to order 1.

The reason your example fails is because the matrix is smaller than the Krylov dimension. Normal packages (like Arpack.jl or Numpy/Scipy), which specifically require that vectors used in these iterative methods are of the native vector type of that language, know the total dimension of the problem. When they see the total dimension is smaller than the Krylov dimension, they can just generate a complete basis and are essentially equivalent to full diagonalisation.

With my package, vectors can be of arbitrary user type and it is not even assumed `length(v)` exists. Note that your matrix only has 6 distinct eigenvalues. The argument that a single random starting vector `v` has only support on a one-dimensional subspace of every eigenspace implies that, after applying the operator 5 times, an invariant subspace is formed spanned by `v`, `Av`, `A^2v`, `A^3v`, `A^4v`, `A^5v`, i.e. when forming `A^6v` and subtracting the components along those previous 6 vectors (or some orthonormal linear combination thereof), the residual vector has a norm which will be essentially zero, i.e. of the order of machine precision and well below the specified tolerance. So, at that point, it just decides that it has found an invariant subspace, returns the 6 eigenvalues it contains (every eigenvalue only once), and returns. That's also what you see, you see every eigenvalue appearing once.

If it would know that the problem is 15-dimensional, it could take this final residual vector which is zero up to machine precision, scale it up to norm 1, reorthogonalise it with respect to the 6-dimensional subspace already there, and continue with this to detect another 6 dimensional subpsace. But since my package does not use `length(v)`, it does not know that the true problem is 15-dimensional. Maybe the true problem was only 6-dimensional, the norm of the residual would equally well be zero up to machine precision.

But then again, in practice, where you apply this approach to big problems where the number of distinct eigenvalues is much larger than the krylov dimension, this would not really be an issue. You will never end up in the case where the whole subspace being formed acts as an invariant subspace.

**Comment by mwallerb** [comment]
Thanks a lot again for the detailed explanation!  I think I got it now :-)
