### ISSUE TITLE
"Access to undefined reference" when using a `Vector` in exponentiate

### ISSUE THREAD

**Issue by PierreGuilmin** [Jutho/KrylovKit.jl#63]
Thanks for this great package! 👏 

I am using the `exponentiate` method to solve coupled linear homogeneous ODEs on matrices, for example:

$$
\begin{align}
\frac{d}{dt}X_t &= X_t + Y_t \\
\frac{d}{dt}Y_t &= 2 * X_t - Y_t
\end{align}
$$

where $X_t$ and $Y_t$ are $2\times 2$ matrices.

It turns out that using a vector for the `x` argument of `exponentiate` raises an error, contrary to what's mentioned in the documentation:
> The linear map `A` can be an `AbstractMatrix` (dense or sparse) or a general function or callable object that implements the action of the linear map on a vector. If `A` is an `AbstractMatrix`, `x` is expected to be an `AbstractVector`, otherwise `x` can be of any type that behaves as a vector and supports the required methods (see KrylovKit docs).

I am probably missing something obvious, here's a minimal example:
```julia
> X0 = [1.0 2.0; 3.0 4.0]
> Y0 = [0.0 1.0; 1.0 2.0]
> x0 = [X0, Y0]
> println(typeof(x0))
Vector{Matrix{Float64}}
> A(x) = [x[1] + x[2], 2 * x[1] - x[2]]
> exponentiate(A, 1.0, x0)
UndefRefError: access to undefined reference
...
```

**Comment by Jutho** [comment]
KrylovKit supports any type that supports a minimal interface for "vector-like behaviour", described on the first page of the docs: https://jutho.github.io/KrylovKit.jl/stable/

This interface is supported by `Vector{<:Number}` and most other `AbstractVector{<:Number}` types, but notably not, for nested arrays, like your `Vector{Matrix{Float64}}`. The problem is that this is outside of my control. The interface that I describe is the best I could do in coming up with a consistent `vector-like behaviour` interface extracted from functions defined in Julia's `Base` and `LinearAlgebra` libraries.

Nested arrays as a representation of e.g. block matrices etc are not consistently supported in Julia; some functionality works (like `dot`) but other does not. The short-term solution is to write a simple wrapper type that does implement the required interface correctly. Maybe a package like [BlockArrays.jl](https://github.com/JuliaArrays/BlockArrays.jl) might help, and does maybe satisfy the necessary interface (I have to admit I have not tested this).

However, I have myself been frustrated with the inconsistent support for nested arrays, and the lack of a well defined vector interface in Julia. KrylovKit in particular has been my main motivation for developing (at this very moment) the package https://github.com/Jutho/VectorInterface.jl . This package fully supports nested arrays, however using a new interface, i.e. a new set of functions (there is no other way to modify behaviour for `Base` types without committing type piracy). It is my plan to base future versions of KrylovKit.jl on VectorInterface.jl, which would straight away make KrylovKit.jl compatible with a much wider range of types, in particular, any nesting of standard vectors, tuples and scalars ...

**Comment by PierreGuilmin** [comment]
Alright I understand, thanks a lot for the detailed answer.

Do you think modifying the proposed code for the following is a temporary viable solution?
```julia
> x0 = [1.0 2.0; 3.0 4.0 ;;; 0.0 1.0; 1.0 2.0]
> println(typeof(x0))
Array{Float64, 3}
> A(x) = [x[:, :, 1] + x[:, :, 2] ;;; 2 * x[:, :, 1] + x[:, :, 2]]
> exponentiate(A, 1.0, x0)
```

**Comment by PierreGuilmin** [comment]
Alright, it's a bit verbose, but it will do for now. I am closing the issue, thanks again for your help!

**Comment by Jutho** [comment]
Look out for a version 1 of KrylovKit (I am not even going to try to estimate a timeline/deadline), which should bring many improvements next to building on top of VectorInterface.jl
